version: "3.8"
services:
  nginx01:
    container_name: "nginx01"
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./proxy01/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy01/log:/var/log/nginx
    networks:
      web_segment:
        ipv4_address: 192.168.1.2
  nginx02:
    container_name: "nginx02"
    image: nginx:latest
    ports:
      - 8081:80
    volumes:
      - ./proxy02/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy02/log:/var/log/nginx
    networks:
      web_segment:
        ipv4_address: 192.168.1.3
  host:
    container_name: "host"
    image: nginx:latest
    volumes:
      - ./host/nginx.conf:/etc/nginx/nginx.conf
      - ./host/log:/var/log/nginx
    networks:
      web_segment:
        ipv4_address: 192.168.1.4
  app:
    container_name: app
    ports:
      - "8082:80"
    build:
      context: ./app
      target: local
    volumes:
      - ./app:/app
    command: air
    networks:
      web_segment:
        ipv4_address: 192.168.1.5
networks:
  web_segment:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24